apply guideline: https://github.com/chilicuil/learn/blob/master/sh/guideline.md, this was a huge commit

diff --git a/sh/tools/mail b/sh/tools/mail
--- a/sh/tools/mail
+++ b/sh/tools/mail
@@ -2,22 +2,22 @@
 #description: send emails
 #usage: mail to@domain.tld "message"
 
-from='No reply <noreply@correo.io>'
-api='api:key-6sm2ioqhxobacydr5qgzljqdxllhs-j4' #try to use your own api key when possibly
+from="No reply <noreply@correo.io>"
+api="api:key-6sm2ioqhxobacydr5qgzljqdxllhs-j4" #try to use your own api key when possibly
 
 _usage()
 {
-    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` MAIL_ADDRESS MESSAGE"
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') MAIL_ADDRESS MESSAGE"
     exit 1
 }
 
 _validmail()
 {
-    [ -z "$1" ] && return 1
+    [ -z "${1}" ] && return 1
 
-    case "$1" in
+    case "${1}" in
         *@*) return 0 ;;
-        *) return 1 ;; 
+        *)   return 1 ;;
     esac
 }
 
@@ -26,11 +26,14 @@ if ! command -v "curl" >/dev/null 2>/dev/null; then
     exit 1
 fi
 
-[ "$#" -lt 2 ] && _usage
+[ "${#}" -lt "2" ] && _usage
 
-if ! _validmail "$1"; then
-    printf "%s\\n" "invalid email address: $1"
+if ! _validmail "${1}"; then
+    printf "%s\\n" "invalid email address: ${1}"
     _usage
 fi
 
-curl -s --user $(printf "%s" "$api" | tr 6 3) -G https://api.mailgun.net/v2/correo.io/messages -F from='No reply <noreply@correo.io>' -F to="$1" -F subject="Automated mail from $(hostname)" -F text="$2"
+curl -s --user "$(printf "%s" "${api}" | tr 6 3)" \
+    -G https://api.mailgun.net/v2/correo.io/messages \
+    -F from="${from}" -F to="${1}" \
+    -F subject="Automated mail from $(hostname)" -F text="${2}"
